### ISSUE TITLE
How to set data driven parameter extension to load value 'All' by default when it loads?

### ISSUE THREAD

**Issue by prasadcool** [tableau/extension-data-driven-parameters#11]
Hi @KeshiaRose  ,
Thank you for developing such a awesome extension. I am using this extension to auto update the parameter on changing the backend data. I have enabled the option to include value '(All)' in the parameter list. But when I try to reload the extension it by default selects the first value from the list but not the value '(All)'.
Can you please guide me on how should I make the extension to select the value'(All)' by default?
Also, can you please guide me on the use of the 'Automatically reset values on load' option?

Regards,
Prasad Kulkarni

**Comment by KeshiaRose** [comment]
Hi @prasadcool,

When you save your configuration, the default is to set it to the first value after (All). However if you set it to (All) and save the workbook, whenever you open it, it will remain set to (All). 

The option to "Automatically reset values on load" is for when you want the parameter to change to the most recent (max or min) value in the list. It has nothing to do with updating the parameter based on data, the parameter will do that automatically. If you want to show (All) as default, turn that option off.

Take care,
Keshia
