### ISSUE TITLE
Multiselect - selections are gone when we change the filter on other fields

### ISSUE THREAD

**Issue by Bharath2205** [tableau/extension-data-driven-parameters#12]
Hi ,

First of thank you so much for making this happen. Its really awesome. 
We just started using multiselect feature and we found a bug. When we select the values and go and after that when we change the filters on other fields, the selections on multiselect would go away. Is there anything you could do immediately on this issue?
And I am also eagerly waiting on other fixes like dropdown and having boxes etc.

Have a great day...!!
Again thank you so much for your work..!!

Thanks,
Bharath

**Comment by KeshiaRose** [comment]
Hi @Bharath2205,
I just made some updates to multi-select. Can you re-configure the extension and let me know if you are still having this issue. If so I will re-open and investigate.

**Comment by KeshiaRose** [comment]
Had some issues with the new updates so I rolled them back until we can confirm everything is good. But here is an [alpha](https://github.com/tableau/extension-data-driven-parameters/raw/master/public/DataDrivenParameters_Alpha.trex) with the updates. Please do not use the alpha in production as it can change or be removed any time but let me know how it works for you, if it solves your issue and if you come across any bugs!

**Comment by KeshiaRose** [comment]
Hi @Bharath2205,

I released the fix and updates as a version 2.0.0. You can now upgrade to get the new features: https://extensiongallery.tableau.com/products/27 

Take care,
Keshia
