### ISSUE TITLE
Unable to select from list

### ISSUE THREAD

**Issue by JohnDelahunt** [tableau/extension-data-driven-parameters#14]
When I select a value from the list in the Data-Driven Parameters extension three things happen:
1. The parameter is changed to the selected value
2. The list is re-loaded
3. The parameter is reset to the first item in the list.

Is it possible that I have something set so as to trigger this behavior?  Any help would be appreciated.

**Comment by JohnDelahunt** [comment]
Through testing, I have discovered the root cause of the problem:  the parameter value cannot be found in the list after the refresh if it includes consecutive spaces.  For example "Red fish" would work fine but "Blue     fish" would not.

I don't have control over the data and I'd rather not use the SQL in the Data Source to try to "fix" it as it loads

**Comment by KeshiaRose** [comment]
Hi @JohnDelahunt,
I've made some new updates to the extension and fixed a reloading issue. Could you please re-configure the extension and see if you are still seeing this error? If that doesn't work also try turning off the new "Update list of values on parameter change." feature which is on by default (as it matches original functionality). Let me know if this works for you, if not I'll re-open and investigate.

Take care,
Keshia

**Comment by KeshiaRose** [comment]
Had some issues with the new updates so I rolled them back until we can confirm everything is good. But here is an [alpha](https://github.com/tableau/extension-data-driven-parameters/raw/master/public/DataDrivenParameters_Alpha.trex) with the updates. Please do not use the alpha in production as it can change or be removed any time but let me know how it works for you, if it solves your issue and if you come across any other bugs!

**Comment by JohnDelahunt** [comment]
@KeshiaRose The problem with items containing multiple spaces has been resolved.  Thank you.

**Comment by KeshiaRose** [comment]
Glad to hear it!

I released the fix and updates as a version 2.0.0. You can now upgrade to get the new features: https://extensiongallery.tableau.com/products/27 

Take care,
Keshia
