### ISSUE TITLE
When trying to set "Select a field" it is loading but not showing any fields to select

### ISSUE THREAD

**Issue by Bharath2205** [tableau/extension-data-driven-parameters#15]
Hi Keisha,

When we are trying to configure the dashboard extension it is not letting us select the field. It just shows loading. Please note that I already have another dashboard extension on the same dashboard and it works fine. I even tried to remove the other and tried it but still doesn't work. Please help.

please see the below screenshot:

![image](https://user-images.githubusercontent.com/47953474/57999771-70061380-7a8b-11e9-96ce-fc3024a87982.png)

**Comment by KeshiaRose** [comment]
Hi @Bharath2205,

Could you open up the debugger and see if you are getting any errors? Instructions for [Desktop](https://tableau.github.io/extensions-api/docs/trex_debugging.html) and [Server/Online](https://tableau.github.io/extensions-api/docs/trex_debug_server.html)

Thanks,
Keshia

**Comment by Bharath2205** [comment]
I found a workaround for this. When I remove a sheet from a dashboard and configure the dashboard extension and then put that sheet back, then it is allowing me to select the field.
