### ISSUE TITLE
[URGENT] Data Parameters not working

### ISSUE THREAD

**Issue by charliech621** [tableau/extension-data-driven-parameters#19]
It works very well before, but it's not able to pass parameters since this morning.
Should I download a new version of extension or anything to fix?
(Mine shows version 0.7.0 now)

Thanks!

**Comment by charliech621** [comment]
It doesn't work in both Desktop (2018.3 to 2019.2 version) and Server (2018.3 version).
Please would you help if anything we could do to fix this?
Many thanks for your help on this !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by stone19880317** [comment]
I find the same error on my Tableau Desktop!

**Comment by caplock** [comment]
I got the same issue with my dashboards. Parameters can neither be passed within the same workbook nor through URL action. The same issue is found on both Tableau Desktop and Tableau Server. 

I sincerely hope this issue can be fixed asap as my users are using the dashboard pretty frequently.  :(

Many thanks!

**Comment by KeshiaRose** [comment]
Hi all, I have reverted the last change for now but could you give me more details on what you mean by "it doesn't work"?

Take care,
Keshia

**Comment by KeshiaRose** [comment]
Also, what kind of values are you using in the parameter?

**Comment by KeshiaRose** [comment]
And what is your locale?

**Comment by KeshiaRose** [comment]
@charliech621 @stone19880317 @caplock  Also please include a screenshot of your settings

**Comment by caplock** [comment]
Thanks Keshia for your replies!

My dashboard contains a parameter tab for users to select the period, category and brand they want to look at. The filter values will then be passed to parameters through the data-driven parameter extension. Other tabs in the dashboard will then refresh based on the values of the parameters. I have run several tests on my dashboard just now and here is the result:

Step 1: I opened the parameter tab in a new browser  Then clicked “Allow” on the pop up window
Step 2. Selected period, category and brand (i.e. filter values) 
Step 3: Then I went to other tabs and data was not refreshed
Step 4: Immediately after I went back to the parameters tab again without changing anything, a loading sign appeared for about 5 second
Step 5: Then I open the other tabs and all data was refreshed based on the filter values

The dashboard could always refresh automatically in step 2 before today. : (

**Comment by KeshiaRose** [comment]
@caplock So you are still seeing this new behavior even with the code back to the way it was? When did you start seeing the problem? Was it before the new update, around 7:00 PM PDT yesterday.

**Comment by caplock** [comment]
@KeshiaRose Yes, I still see the new behavior now. 

I first saw the problems around 9 hours ago and there were some layout changes in the configuration page. At that time, the data-driven parameters did not work no matter how many times I went back and forth from the parameter tab to the others.

Now that the configuration page has reset to the previous version, the extension is still not fully functioning as described in my last reply.   : (

**Comment by KeshiaRose** [comment]
Hmm, I tried reproducing what you described with the new version and could not get the same issue. Would you be able to make a mock workbook and send it to me at krose@tableau.com so I can test? make sure you are seeing the same issues that you see with your real dashboard.

**Comment by KeshiaRose** [comment]
Hi @charliech621, @stone19880317, & @caplock,

I've created an alpha build with the new features you can download [here](https://github.com/tableau/extension-data-driven-parameters/raw/master/public/DataDrivenParameters_Alpha.trex). Please try out this new version and confirm that it works or does not work. If it doesn't work please include the errors from the console log. Instructions on using the debugger to get the errors can be found in the documentation: [Desktop](https://tableau.github.io/extensions-api/docs/trex_debugging.html) or [Server/Online](https://tableau.github.io/extensions-api/docs/trex_debug_server.html).

Thanks,
Keshia

**Comment by stone19880317** [comment]
Hi @KeshiaRose ,
i open the twbx saved yesterday and the data-parameters can working well.Thanks~

**Comment by stone19880317** [comment]
Hi @KeshiaRose 
I find when i published the dashboard on Tableau Server, the data-parameters can't working but in Tableau Desktop its ok....

**Comment by charliech621** [comment]
@KeshiaRose Thanks much for your prompt help! I tried again for the workbook on both Desktop and Server and it seems working now.

For the alpha you have built with new features, I am not quite sure how to apply to the existing extension and test. Would you please advise?
And what's the difference with the existing version we are using?

Kind Regards,
Charlie

**Comment by stone19880317** [comment]
@charliech621 The Data-parameter can be used in Tableau Desktop and Tableau Server?It's all OK?

**Comment by charliech621** [comment]
@stone19880317 yes it seems working well now. Is it still not working in your dashboard?

**Comment by stone19880317** [comment]
@charliech621 Its working well on my Desktop but on the Server its not ok.

**Comment by caplock** [comment]
@KeshiaRose Thanks for providing the new version!
I tried it again today. It didn't work at until I rest all selections in the configuration. It's now working on both desktop and server. Thanks a lot!

**Comment by stone19880317** [comment]
@caplock @charliech621 @KeshiaRose  Hi all, If i do something after published the workbook on Tableau Server?For example,  must be installed some utilities?

**Comment by caplock** [comment]
@stone19880317 I didn't install any new. All I did was just to reset all settings in configuration. 
I suppose the new changes made by @KeshiaRose can be triggered when you open the dashboard and allow the extension to run

@KeshiaRose Not sure if the above understanding is correct. Would be great if you could advise if any necessary steps we have to follow to reflect the new changes in the dashboard : )

**Comment by stone19880317** [comment]
@KeshiaRose When i published the workbook on the Server, its notes  "No extensions are allowed on this server. Contact your server administrator to change this setting to allow the extender.". If i need install some apps???

**Comment by KeshiaRose** [comment]
Hi all, thanks for all the updates!

@stone19880317:  It looks like you never had the ability to use the extension on the Server in the first place, and not a new issue after the upgrade attempt. Is that right? That error is caused by Server settings and you will need to have an admin turn on extensions or safe-list this one to use it. More info [here](https://onlinehelp.tableau.com/current/server/en-us/dashboard_extensions_server.htm).

@charliech621: Glad it is working again for you. For testing the alpha, [download the new trex](https://tableau.github.io/extension-data-driven-parameters/alpha/DataDrivenParameters_Alpha.trex), treat it as a brand new extension and drag it into your dashboard. Configure it as you would normally and let me know if you come across any errors. The alpha includes some new features and bug fixes over the current version.

@caplock: Glad it is working for you again. You are right that new updates are triggered automatically when you open the dashboard. There have been several updates already but this was a big one and wasn't so seamless. Could you also give the [alpha](https://tableau.github.io/extension-data-driven-parameters/alpha/DataDrivenParameters_Alpha.trex) a try and let me know if you get any errors?

Take care,
Keshia

**Comment by KeshiaRose** [comment]
I've added the new features to version 2.0.0. Please upgrade and let me know if you come across any issues!

https://extensiongallery.tableau.com/products/27

Take care,
Keshia

**Comment by scaffarelli** [comment]
Hi @KeshiaRose seems that I'm facing this issue in Tableau Desktop, do you know if the extension is working?

**Comment by KeshiaRose** [comment]
#48

**Comment by lorettaxia** [comment]
HI Keshia,

again first thanks for this useful extension! 
but the extension didn't work yesterday? were you aware of that? just wonder why? it was such a bad luck that I was in the middle of a presentation yesterday! ;p

thanks,
Loretta

**Comment by KeshiaRose** [comment]
Hi @lorettaxia, 

I'm so sorry to hear that! I didn't make any changes to the extension recently so I'm not sure what happened during your presentation. Could you please open a new issue and tell me more about how it didn't work?

Take care,
Keshia
