### ISSUE TITLE
Unexpected Error popup related with the date extension

### ISSUE THREAD

**Issue by sdoyle18** [tableau/extension-data-driven-parameters#20]
Hi we are getting this error on random occasions we believe is related to the extension we are using in the dashboard:

![image](https://user-images.githubusercontent.com/51175817/58586806-ee9c4700-8229-11e9-86fa-4b13cc554158.png)

The only thing I could find on the issue was this thread here: https://community.tableau.com/thread/296491
which doesn't really provide any solution to stopping the error from appearing. 

Any additional information on preventing this error from occurring would be appreciated. Thanks

**Comment by KeshiaRose** [comment]
Hi @sdoyle18,

Can you tell me what version you are on and if you are in Tableau Server or Online?

Take care,
Keshia

**Comment by sdoyle18** [comment]
Hi Keshia,

Tableau version 2019.1
The dashboard is embedded in a web application where the error appears, on Tableau Server

**Comment by KeshiaRose** [comment]
Hi @sdoyle18,

Can you include the third number as well? Example: 2019.1.3. I think we already have a fix for this but trying to confirm.

Take care,
Keshia

**Comment by sdoyle18** [comment]
I believe we are on Version 2019.1.1

**Comment by KeshiaRose** [comment]
Hi @sdoyle18,

Got it, yes, this issue is already fixed within the latest maintenance release. To see it applied you will need to upgrade your server to 2019.1.4.

Take care,
Keshia
