### ISSUE TITLE
Having trouble following instructions for "How to install for local use"

### ISSUE THREAD

**Issue by JohnDelahunt** [tableau/extension-data-driven-parameters#21]

**Comment by JohnDelahunt** [comment]
Step 4 (run "yarn build") removes the docs folder.  Then Step 5 requires copying the docs folder.  How do I do that?

**Comment by KeshiaRose** [comment]
Hi @JohnDelahunt,

Yarn build should remove and recreate the docs folder so it should be there when you're done. You can also just use `react-scripts-ts build` and copy the files from the `build` folder.

Take care,
Keshia

**Comment by JohnDelahunt** [comment]
What do I need to change so that yarn build recreates the docs folder as it should?

**Comment by JohnDelahunt** [comment]
Never mind.  The mv command in package.json is invalid under Windows 7.  Rewriting that portion of the file to use md/copy/del instead works wonders.
