### ISSUE TITLE
After selecting the values from the filter shows only some values in dropdown

### ISSUE THREAD

**Issue by Bharath2205** [tableau/extension-data-driven-parameters#22]
When selecting the values from the filter then again go to that filter to select other values in dropdown shows only some values. basically filtering the values in the dropdown after a selection show only some values not all values.

**Comment by KeshiaRose** [comment]
Hi @Bharath2205,

The values in the drop down are based on the values in the source worksheet. So, if you filter the values on the sheet, the dropdown will have only the new filtered items.

Take care,
Keshia

**Comment by Bharath2205** [comment]
Thank you Keshia for the quick reply...!!
