### ISSUE TITLE
IE11 compatiblity issue

### ISSUE THREAD

**Issue by catbkit** [tableau/extension-data-driven-parameters#23]
Extension continuously shows "Loading" in IE11.  Works appropriately in Chrome and Edge.

**Comment by KeshiaRose** [comment]
Hi @catbkit, 

Thanks for the heads up, I've fixed the issue! Please reopen if you are still seeing the issue upon refresh.

Take care,
Keshia

**Comment by MattVoda** [comment]
Keshia,
I'm still experiencing this issue, referencing the main Github build's URL. 
Also curious what this problem was / is, if you're able to share any interesting details!
Thanks for prompt responses to all our past issues!
--Matt

**Comment by KeshiaRose** [comment]
Hi @MattVoda,

Can you try using version 2.0 and seeing if you still see this issue? https://extensiongallery.tableau.com/products/27

Take care,
Keshia

**Comment by MattVoda** [comment]
Sorry should have mentioned, I've been running 2.0.0 when experiencing the issue.

**Comment by KeshiaRose** [comment]
Hi @MattVoda,

This is a different issue than the original one stated. Looks like it started when I updated the extension to use the latest version of react-scripts 3 days ago. This new version has stopped supporting IE11 and does not include by default the necessary polyfills which are needed for modern javascript to run in older browsers like IE11. I've added the necessary polyfills and it should now work for you upon refreshing your browser. Either way though, I suggest moving on to a more modern browser like Chrome or even Edge which supports modern technologies.

Take care,
Keshia

**Comment by MattVoda** [comment]
Thanks Keshia!! Such a fast fix. I was concerned about using this plugin in our production dashboards, but your responsiveness has completely nullified those concerns. 
And yes, it's been a struggle to get a large chunk of users onto modern browsers. The power of defaults...
