### ISSUE TITLE
Version 2 not updating parameter automatically

### ISSUE THREAD

**Issue by wweber713** [tableau/extension-data-driven-parameters#24]
The current release does not work on Tableau desktop. We have a sheet with a list of short strings and an open parameter that the extension should update - but the update only works when you reload the extension or if you allow for multi-selection and they use the apply button (if you choose one even it works with the apply button). The single select option does not work still. An old version works perfectly though, version 0.7.0.

**Comment by KeshiaRose** [comment]
Hi @wweber713,

I'm unable to reproduce your issue. Could you please provide some more details on your environment or provide a sample workbook? What version of Tableau are you on?

Take care,
Keshia

**Comment by wweber713** [comment]
Apologies, I cannot replicate the issue myself now and believe the error was on the end user connecting it to a parameter that did allow all values, but had a value already in place. I'm able to get it to work properly.

**Comment by KeshiaRose** [comment]
No worries! 😃
