### ISSUE TITLE
Question: Installing in a multi-node environment

### ISSUE THREAD

**Issue by MattVoda** [tableau/extension-data-driven-parameters#25]
Hi,

Sorry if this is a bit out of the scope of this specific extension, but couldn't find any info online.

My company runs 3 Tableau Server environments, each with 3 nodes. If I want to install and host this extension locally for one of these environments, do I need to install and host on each node, or just one?

I'm operating at the edge of my knowledge with regards to hosting/serving, so apologies if my terminology is a bit off.

**Comment by KeshiaRose** [comment]
Hi @MattVoda,

Extensions do not need to be hosted on every node just on one machine that all nodes of Tableau Server can access. I would suggest hosting it centrally on a separate internal machine that is not one of the ones you are using as Tableau Servers.

Take care,
Keshia
