### ISSUE TITLE
When dashboard loads in tableau server parameter gets reset to first value

### ISSUE THREAD

**Issue by alexsweet** [tableau/extension-data-driven-parameters#26]
Tableau Server: 2019.2.1
Tableau Desktop: 2019.2.1

First off - love the extension! When publishing a dashboard to Tableau server the data driven parameter is reverting to the first value in the option list. I have published versions with both _Automatically reset values on dashboard load_ checked and unchecked and neither changes this behavior.

**Comment by KeshiaRose** [comment]
Hi @alexsweet,

Are you using version 2 of the extension? You can check in the about menu for the extension. Also what settings are you using? What data type for the parameter?

Take care,
Keshia

**Comment by alexsweet** [comment]
Version 2.0.0, using an Integer data type, sorting descending & using a different field to display values (String field). Other checkboxes are not checked (though I have tried it with the Automatically reset values on dashboard load checked).

**Comment by KeshiaRose** [comment]
Hi @alexsweet,

I was able to repro what you were seeing, good catch! Currently, we return parameter values as strings and it wasn't finding a match for the integers. I've updated the extension and you should now see the values persist when publishing.

Take care,
Keshia
