### ISSUE TITLE
Not loading for morethan 50,000 records

### ISSUE THREAD

**Issue by kartheekchk86** [tableau/extension-data-driven-parameters#27]
I have a Data source which has more than 50,000 rows and the parameter not even ready to set configuration. It is showing "Loading..." only. I really need this parameter to work on but hopeless.

**Comment by JohnDelahunt** [comment]
@kartheekchk86: Sounds similar to a case I submitted.  It was resolved by a recent re-build using an updated React library.  Make sure you're using the most recent code.  50,000 items won't be instantaneous but it will work in a little over a minute for me now.

**Comment by KeshiaRose** [comment]
Hi @kartheekchk86, 

As John suggested, loading that many items will take some time. Were you able to see the items after some time? Also, can you do a test with a smaller amount of data in order to determine it is not some other issue?

Take care,
Keshia

**Comment by kartheekchk86** [comment]
HI @KeshiaRose, 

First of all  Thank you very much for the wonderful extension. 
I am unable to configure the parameter in Tableau Desktop unless I remove the other sheets from dashboard with huge data. Data source is not the same for Extension sheet and the 50,000 records. And in Tableau server it is loading but taking more time. 

Thanks,
Karteek

**Comment by KeshiaRose** [comment]
Hi @kartheekchk86,

Hmm. Which field in the configuration is it getting stuck on? Are any of them loading? Also, is it possible to filter down the number of items shown on the dashboard? 

Take care,
Keshia

**Comment by kartheekchk86** [comment]
Hi @KeshiaRose ,
I have a parameter of date type, and when there is a sheet with approx 50K records, then Parameter is simply showing "Loading..."
When I remove the huge data sheet then only Configuration window is opening. And after configuration it is showing " Loading..."If I add the sheet back. 


![Data driven Parameter Loading error](https://user-images.githubusercontent.com/52913211/61458665-5a1dad80-a96b-11e9-814c-06dde918b20e.PNG)

**Comment by KeshiaRose** [comment]
Hi @kartheekchk86,

It may just be struggling to get all the data. If you put a filter on the big data source sheet to bring down the number of rows, does it work then?

Take care,
Keshia

**Comment by kartheekchk86** [comment]
Sorry but didn't understand the question. ఈ am comparing the parameter date with another date field in 2 different data sources. Just to make a quick load I used extension with less data source. After publishing Filter happening perfectly with extension in server

**Comment by KeshiaRose** [comment]
Hi @kartheekchk86,

I'm not really sure what is happening then, if it works with a smaller data source and not with the bigger one it might just be taking a really long time to load. 

Take care,
Keshia
