### ISSUE TITLE
Getting error while importing .trex file for the Data Driven Parameter v2.0

### ISSUE THREAD

**Issue by JyotiSingh7** [tableau/extension-data-driven-parameters#28]
I am getting error while importing the new version (where updates has been added to automatically update the parameter values) of Data Driven Extension into my Tableau.
I am getting the below error, can somebody help me if I am missing something here?

![image](https://user-images.githubusercontent.com/49139415/61349436-c45a2380-a881-11e9-89b8-5926b4c4e57f.png)

**Comment by KeshiaRose** [comment]
Hi @JyotiSingh7,

Looks like something is wrong with the manifest file. Can you try downloading a fresh copy of the trex file? https://extensiongallery.tableau.com/products/27 Also, what version are you on?

Take care,
Keshia

**Comment by JyotiSingh7** [comment]
Hi Keshia,
Thanks for your reply!

PFA the attached .trex file I am trying to use and I downloaded that from the extension gallery link you have shared.
When I import the file into my Tableau desktop, it seems like the old version of the Data Driven Parameter; and as mentioned in the description about this updated Data Driven Parameter there is “automatic update of parameter values” has been added, but it does not seem to work for me.

Also, the configuration screen I am getting for this is attached below and I am not getting any option for “Filter parameter list based on worksheet selection” option in the configuration screen.
[cid:image002.jpg@01D53D6D.187C8140]
However, it is shown in the screenshots present on the portal; that I should be getting below configuration screen.
Link for the same :  https://extensiongallery.tableau.com/products/27
PFB the screenshots present there, which I should be getting for this new upgraded version of Data Driven Parameter:

[cid:image003.jpg@01D53D6D.187C8140][cid:image004.jpg@01D53D6D.187C8140]

Can you please check if the .trex file I am using is correct and is there anything else in settings I am missing to get the “Automatic Update for the Parameters” enabled?
Please let me know if you need any further details from my end.


Thanks,
Jyoti Singh
Mob: 7022521113

**Comment by KeshiaRose** [comment]
Hi @JyotiSingh7,

The attachments didn't make it through the email, could you try attaching them through the site? Also, did you try downloading a new copy? Perhaps you still have the old one or it has gotten corrupted. But, it seems like now you have gotten past the error and are seeing the configuration dialog? 

Take care,
Keshia

**Comment by JyotiSingh7** [comment]
Hi @KeshiaRose ,

[DataDrivenParametersSummary.zip](https://github.com/tableau/extension-data-driven-parameters/files/3410840/DataDrivenParametersSummary.zip)

Please find the attached .trex file I got from the extension gallery.
This is the new copy itself and URL mentioned in the file is also version 2.0.

Yeah I got past the error, but it seems the configuration dialog which I get through this .trex file is for the old version of Data Driven Parameter. Because I dont get any such options for "filter parameter based on worksheet selection" as I earlier also mentioned.

Not sure if the file I am downloading from the gallery is for the upgraded version.
If the new copy .trex is working for you, will you be able to provide me the same?

Thanks Again for all your help!
Jyoti

**Comment by KeshiaRose** [comment]
Hi @JyotiSingh7,

Yup that is the right one and works for me. Can you send me a screenshot of what options you are seeing on the options tab (tab 2 of 3) of the configuration dialog?

Take care,
Keshia

**Comment by JyotiSingh7** [comment]
Hi @KeshiaRose ,

PFB the attached screenshots for the 2 and 3 dialog boxes.
Its strange the same file is not working for me..
![Screenshots_DialogBox](https://user-images.githubusercontent.com/49139415/61551985-49a52a00-aa74-11e9-80a5-3df601936448.png)

Thanks,
Jyoti

**Comment by KeshiaRose** [comment]
Hi @JyotiSingh7,

Sorry, maybe I misunderstood your question. Are you saying the "Filter parameter list based on worksheet selections" option isn't working for you? I see it in your screenshot. That is the current version of the extension.

Take care,
Keshia

**Comment by JyotiSingh7** [comment]
Hi @KeshiaRose ,
Yeah, that's correct.
I am not getting the version 2.0 for the Data Driven Parameter where the automatic update has been implemented.
You can refer the link where the details are present for the same in the Tableau Extension Gallery and screenshots are also present there.
https://extensiongallery.tableau.com/products/27

Thanks,
Jyoti

**Comment by KeshiaRose** [comment]
Hi @JyotiSingh7,

The extension you have is version 2, the latest version. It has the automatic update option as you can see in your options tab. Note that the extension already updates the list based on data automatically, that option is only if you want to reset the default value on load. The images in the gallery are from when I first made the extension and show the old version. I've just uploaded some new images, clear your cache and refresh to see them (Ctrl + F5). I'm going to close this issue, let me know if you are still having trouble setting up the extension.

Take care,
Keshia
