### ISSUE TITLE
Multi select

### ISSUE THREAD

**Issue by ekholmer** [tableau/extension-data-driven-parameters#3]
Hi,

Would it be possible to add the ability to multiselect?
And that you can choose your own delimiter. 

Thanks a lot for this extension, it is awesome!

**Comment by KeshiaRose** [comment]
Thanks for the suggestion! I just added this feature, let me know what you think!

**Comment by KeshiaRose** [comment]
Glad you like it! I want to add the things you suggested but those controls are a lot trickier for me to create than the standard HTML elements. I do like the idea of adding an apply button though, and that wouldn't be as hard since it's just adding a button and changing when the parameter update happens. I'm heading out for vacation after today but you can expect that option next year! Thank you so much for the feedback, it's nice to hear your ideas and that you are getting benefits from it! :)

**Comment by ekholmer** [comment]
Hi Keshia,

I found a bug. If you put a space as the first letter in the attributs, you
cannot change the attribut. I will just go back to the first selected one.

The reason that I put space in the first letter is when I want a specific
value to come up as standard based on a formula. I my case weeknumbers.

Thanks and regards,
Henrik

Den fre 21 dec. 2018 kl 17:54 skrev Keshia Rose <notifications@github.com>:

**Comment by KeshiaRose** [comment]
Hi Henrik,

Could you paste this into a new issue, just so I can keep track of it? Also, I'm unable to repro what you are seeing, could you send me a sample workbook? You can just use superstore. or even just some screenshots? (krose@tableau.com)

Thanks,
Keshia

**Comment by tamirgilany** [comment]
> That was fast, thank you so much!
> 
> It works great. To make it a little bit more user friendly, could you make it look more like a multiselect dropdown filter in Tableau including an apply button?
> 
> In other words,
> 
> 1. Add the ability to search within the filter.
> 2. Add checkboxes for selecting values in the filter.
> 3. Change the multi select version to also be a drop down.
> 4. When you chose the multiselect option, add an apply button to write your selections to the parameter. This is to avoid loading time between selections if the user want to select a lot of different values.
> 
> This extension make my dashboards much faster and also more user friendly. I can’t thank you enough! :)

Hey @KeshiaRose,

Is there any update regarding this issue, or an estimation for when such features would be available??

Thanks!

**Comment by KeshiaRose** [comment]
Hi @tamirgilany,

I would say sometime in the next month or so I will be able to add some of these features. Is there one in particular you are interested in?

Take care,
Keshia

**Comment by TGilany** [comment]
> Hi @tamirgilany,
> 
> I would say sometime in the next month or so I will be able to add some of these features. Is there one in particular you are interested in?
> 
> Take care,
> Keshia

Hey @KeshiaRose,
Thanks for the quick reply.
I would love to have numbers 1 to 3.

Is there a possibility for a quicker release within less than a month?

Thanks!

**Comment by tamirgilany** [comment]
> Hi @tamirgilany,
> 
> I would say sometime in the next month or so I will be able to add some of these features. Is there one in particular you are interested in?
> 
> Take care,
> Keshia

Hey @KeshiaRose,
Thanks for the quick reply.
I would love to have numbers 1 to 3.

Is there a possibility for a quicker release within less than a month?

Thanks!

**Comment by KeshiaRose** [comment]
Hi @tamirgilany,

Thanks for your feedback, it helps prioritize what to do first! Honestly, it depends on my schedule, so it may come sooner but I don't want to make any promises. However, if this is something you need more urgently, the extension is available for download to enable you to make the modifications on a local instance until these features get added to the official extension. 

Take care,
Keshia

**Comment by KeshiaRose** [comment]
For better feature request tracking I've created separate issues for the features suggested here. Please look to them for updates:
[#8 Feature Request: Add search bar.](https://github.com/tableau/extension-data-driven-parameters/issues/8)
[#17 Feature Request: Add checkboxes to multi-select.](https://github.com/tableau/extension-data-driven-parameters/issues/17)
[#18 Feature Request: Change the multi-select version to be a drop down.](https://github.com/tableau/extension-data-driven-parameters/issues/18)
[#7 Feature Request: Add apply button for multi-select.](https://github.com/tableau/extension-data-driven-parameters/issues/7)
