### ISSUE TITLE
UX Request: Align control size with default Tableau control size

### ISSUE THREAD

**Issue by MattVoda** [tableau/extension-data-driven-parameters#31]
![box sizing](https://user-images.githubusercontent.com/6518882/61916674-6bd8f500-af17-11e9-8df4-0b51997707ee.PNG)

Is there any way to change the dropdown dimensions so it looks in-line with other default Tableau dropdowns? Did you choose to make them larger for a reason? I actually prefer the larger size, but not next to a default dropdown.

**Comment by KeshiaRose** [comment]
Hi Matt,

Refresh for an updated dropdown size! 😃 

Take care,
Keshia

**Comment by MattVoda** [comment]
Wooo!! Many thanks
