### ISSUE TITLE
Feature Request: "(All)" value to be customized  

### ISSUE THREAD

**Issue by anirudhmadhwak** [tableau/extension-data-driven-parameters#32]

**Comment by anirudhmadhwak** [comment]
When checking include"(All)" in parameter list. Can we make sure it can be customized with whatever value the user likes. For ex: "Select Values" or "Select" or "Please Select"

**Comment by anirudhmadhwak** [comment]
will change of this section ( // Add '(All)' according to settings
            if (settings.includeAllValue === 'true') {
                list.unshift({value: '(All)', displayValue: ' Please Select Value'});
            })
in DataDrivenParameter.tsx will give the required result?
Original : // Add '(All)' according to settings
            if (settings.includeAllValue === 'true') {
                list.unshift({value: '(All)', displayValue:  '(All)'});
            })

**Comment by KeshiaRose** [comment]
Hi @anirudhmadhwak,

I don't have time available right now to make this change, but I do like your idea. Yes, that is the spot where you can change the code to whatever value you want. Until I am able to make this an option officially please feel free to make this change in a local copy. I will keep this issue open until I get a chance to add it as a customizable option.

Take care,
Keshia

**Comment by KeshiaRose** [comment]
Hi @anirudhmadhwak,

I've made the update in the latest version of the extension, v2.1.0. Please try it out and let me know how it works for you! [TREX](https://raw.githubusercontent.com/tableau/extension-data-driven-parameters/master/DataDrivenParametersSummary_v2.1.0.trex)

Take care,
Keshia

**Comment by anirudhmadhwak** [comment]
Thankyou for the update @KeshiaRose  its working

**Comment by anirudhmadhwak** [comment]
By default its taking first value in the parameter, even after unchecking 'Automatically Resetting Values on  dashboard load'

**Comment by KeshiaRose** [comment]
Hi @anirudhmadhwak,

Can you make a sample workbook showing me what i going on and send it?

Take care,
Keshia
