### ISSUE TITLE
Feature Request: Cascading of data driven parameters (If we are using more than two data driven parameters extensions)

### ISSUE THREAD

**Issue by anirudhmadhwak** [tableau/extension-data-driven-parameters#33]

**Comment by anirudhmadhwak** [comment]
Let us take two parameters for a hierarchy viz.Product, Sub- Product. I need data dynamically entering into the values and other reasons for going to dynamic parameter. I have created Product parameter as one dynamic parameter and sub-product as other dynamic parameter. If I have selected one Product, the sheet is changing but the other parameter is not getting updated as per first parameter. Is there a way we can achieve this or Is it Possible?

**Comment by anirudhmadhwak** [comment]
![Capture](https://user-images.githubusercontent.com/53763251/62683752-d7719680-b9dc-11e9-8c79-b2063d61d3fd.JPG)

**Comment by anirudhmadhwak** [comment]
It is only updating after selecting some value in sub product parameter. Its not loading dynamically. Its getting refreshed upon click.

**Comment by KeshiaRose** [comment]
Hi @anirudhmadhwak,

Thanks for the idea, I have heard this a couple of times and I am thinking about adding something similar as an option. In the meantime, I made a quick workaround extension that will do this update for you.  Take a look at the attached trex and sample workbook on how to use it. You can find the code below as well. I'll close this ticket when I've added something officially to the extension.

https://glitch.com/edit/#!/param-listener-workaround

[Parameter Listener.zip](https://github.com/tableau/extension-data-driven-parameters/files/3482123/Parameter.Listener.zip)

Take care,
Keshia

**Comment by KeshiaRose** [comment]
Hi @anirudhmadhwak,

I've now added an option for you to listen to the updates of a specific parameter to reload the list. Try it out and let me know how it works for you! [TREX](https://raw.githubusercontent.com/tableau/extension-data-driven-parameters/master/DataDrivenParametersSummary_v2.1.0.trex)

Take care,
Keshia

**Comment by anirudhmadhwak** [comment]
Thankyou for the update @KeshiaRose  its working

**Comment by VigneshSakkaraPandian** [comment]
Hi @KeshiaRose,

Could you please provide me on the steps for how we can cascade two data driven parameters 

Thanks,
Keshia

**Comment by anirudhmadhwak** [comment]
![DataDrivenParameters](https://user-images.githubusercontent.com/53763251/65209142-d0967300-dab4-11e9-8d78-bc50536b64d0.JPG)

**Comment by anirudhmadhwak** [comment]
@VigneshSakkaraPandian you can select from the marked field and drop down for choosing parameters

**Comment by VigneshSakkaraPandian** [comment]
Hi @anirudhmadhwak,

I have selected the same option. But the values are not getting updated when i select the other parameter.
I have attached the sample workbook. kindly help me resolve the issue.

[Test Workbook with parameter ext.zip](https://github.com/tableau/extension-data-driven-parameters/files/3629756/Test.Workbook.with.parameter.ext.zip)

**Comment by KeshiaRose** [comment]
Hi @anirudhmadhwak,

Please try it again, should be working now. Although, I see in your example that you are trying to go in both directions. That will not work as they will both work off each other and you will end up back at the original value.

Take care,
Keshia

**Comment by VigneshSakkaraPandian** [comment]
Thankyou for the update @KeshiaRose its working
