### ISSUE TITLE
Subscriptions not updating

### ISSUE THREAD

**Issue by alivaneerden** [tableau/extension-data-driven-parameters#34]
Hi- I am using the data driven parameter to default my dashboard to the latest date in my data set. The data driven parameter is working as expected, but the daily subscription email does not show the most recent value in the workbook.

It looks like the data driven parameter is triggered in tableau online when the URL refreshes and, I am assuming, a subscription does not refresh the URL so the latest date is not pulled into the dashboard before generating the subscription email.

Does anybody know of a workaround for this? Any help would be GREATLY appreciated! 
Ali

**Comment by KeshiaRose** [comment]
Hi @alivaneerden,

Unfortunately, extensions do not run when subscription images are being generated. We are aware of this but there is no current timeframe for this fix. We still need to investigate what it would take to do it. I've added this issue to internal issue, and when it is fixed I will update you here.

Take care,
Keshia 

_Internal: 895702_

**Comment by alivaneerden** [comment]
Thanks @KeshiaRose  . Have you seen any creative workarounds in the meantime?

**Comment by KeshiaRose** [comment]
Not really, only to create your own custom email subscriptions. 😢

**Comment by KeshiaRose** [comment]
Going to close this here as it pertains to Tableau extensions as a whole and not specifically this extension. Please look for updates over on the extensions-api repo here: https://github.com/tableau/extensions-api/issues/237
