### ISSUE TITLE
Error while adding extension into desktop

### ISSUE THREAD

**Issue by Venkat1505** [tableau/extension-data-driven-parameters#35]
We have followed the steps in implementing the Data Driven parameters and updated the trex file.

But we are getting error when we tried to add the extension into Tableau desktop.

[Extension error.docx](https://github.com/tableau/extension-data-driven-parameters/files/3501559/Extension.error.docx)

**Comment by Venkat1505** [comment]
[DataDrivenParametersSummary_v2.0.0.zip](https://github.com/tableau/extension-data-driven-parameters/files/3501629/DataDrivenParametersSummary_v2.0.0.zip)

**Comment by KeshiaRose** [comment]
Hi @Venkat1505,

The server where you are hosting the extension must be served over HTTP**S** and will not run otherwise unless it is "localhost".

Take care,
Keshia
