### ISSUE TITLE
building on mac

### ISSUE THREAD

**Issue by takashibinns** [tableau/extension-data-driven-parameters#36]
When running this on my mac, i had to change the build command in **package.json** to the following (since _rd_ and _move_ are not valid commands on mac osx)

`"build": "react-scripts build && rm -R docs && cp -R build docs",
`

is there a way to make this build script work across platforms?

**Comment by KeshiaRose** [comment]
Hi @takashibinns,

I just have the extra bits in there just to move files from `build` to `docs` because we are currently hosting it here on GitHub out of the `docs` folder. Feel free to remove the extra bits and just run `react-scripts build` when building locally.

Take care,
Keshia
