### ISSUE TITLE
Parameter Values not passed to other dashboards using the extension

### ISSUE THREAD

**Issue by Smeegs** [tableau/extension-data-driven-parameters#38]
We have the extension in use for the same date parameter in multiple dashboards for selecting a month. We have found that the parameter value is not being consistently passed to subsequent dashboards. 

Only the 'landing page' dashboard has the 'Refresh on Dashboard Load' option selected, with all others having no options selected, but it seems like the starting value of the extension is not being read from the parameter, but instead is refreshing to the last selected value for the specific dashboard.

**Comment by KeshiaRose** [comment]
HI @Smeegs,

Thanks for this feedback. I was able to reproduce what you are seeing. I think this is a quick option I can add, look out for an update next week or so.

Take care,
Keshia

**Comment by KeshiaRose** [comment]
Hi @Smeegs,

Made an update so the parameters should match now when you swap to different dashboards. Note, if you have a lot of data populating the extension it might take a second. 

Take care,
Keshia

**Comment by Smeegs** [comment]
Any updates on this since you had to revert back the fix?

**Comment by KeshiaRose** [comment]
Hi @Smeegs,

I am currently out of town and wasn't about to finish everything before I left. I hope to get a new update out with a couple other additions out by the end of next week.

Take care,
Keshia

**Comment by KeshiaRose** [comment]
Hi @Smeegs,

I've made the update in the latest version of the extension, v2.1.0. Please try it out and let me know how it works for you! [TREX](https://raw.githubusercontent.com/tableau/extension-data-driven-parameters/master/DataDrivenParametersSummary_v2.1.0.trex)

Take care,
Keshia

**Comment by Smeegs** [comment]
Thanks Keshia, we will try it out. One of the issues we have is that since version 2.0.0, with the unique extension URL for each version, we have run into 2 issues:

1. Our Tableau Server setup requires each unique extension URL to be whitelisted, so each update requires us to reach out the the server admin to add the new URL to the whitelist, which can be cumbersome.

2. Each update requires us to remove and re-add the new extension version to each dashboard page. 

- We have the extension in use in multiple workbooks and on multiple dashboards in each workbook. 
- The primary use of this extension was to allow for more hands-off maintenance, but the versioning protocol means that we have to do a significant amount of non-value add busy work to update all of the locations we have the extension in use. Is there an easier way to apply updates, or is our method the only way?

Thanks!

**Comment by KeshiaRose** [comment]
Hi @Smeegs,

The old versions will not be taken down so you don't have to worry about updating all instances unless you want to use a new feature. However, for the future, I've added a new 2.latest version. All future minor updates will go there so you won't need to update your safe-lists or trexs for a dot release.

Take care,
Keshia
