### ISSUE TITLE
Cannot host on internal webserver

### ISSUE THREAD

**Issue by kabelak** [tableau/extension-data-driven-parameters#40]
I've created a webserver on an instance which is within a private VPC, and uses a private DNS (eg: tableau.extensions.company.local). The server works and the extensions page loads in a browser (albeit getting the 'insecure' flag in chrome as a self signed certificate is used). 

My issue: Tableau Desktop will not allow me to use the extension, since it is 'not secure'.

Is there a way for Tableau Desktop (and server) to circumvent the need to have a fully fledged signed certificate from a trusted authority? I will only be using the extensions webserver for the extensions, on a private machine within a private DNS.

Any help, or advice would be appreciated.

**Comment by KeshiaRose** [comment]
Hi @kabelak,

No, there is no way to get around this requirement. All extensions must use HTTPS protocol unless it's on `localhost`. We have some tips on hosting and how you can get free or low-cost certificates here: https://tableau.github.io/extensions-api/docs/trex_security.html#do-it-yourself-diy. Hope this helps!

Take care,
Keshia
