### ISSUE TITLE
Navigation between tabs in workbook have extension causes an error message popup

### ISSUE THREAD

**Issue by FahadAsifGit** [tableau/extension-data-driven-parameters#45]
I have a workbook with multiple tab and each one of this tab have an data drive parameter extension in then referring to same field. When i browser the report in IE-11 it get an Error message popup on switching between tabs (Screenshot).

But the same report works fine on Mozilla and Chrome.
![Capture](https://user-images.githubusercontent.com/55692761/65418841-f0ae9500-de1a-11e9-852e-3dc54d76ccb0.PNG)

**Comment by KeshiaRose** [comment]
Hi @FahadAsifGit,

Sorry for the delay I have been out with the flu. This is a known Tableau Server issue that has already been fixed, are you able to update to the latest maintenance release of Tableau Server? Also, I don't recommend using IE11 anyways unless absolutely necessary. It does not support modern web standards and many developers are not testing for it. I would recommend Chrome, Firefox, or even Edge, Microsoft's modern built-in browser, which can launch IE11 for sites that need backward compatibility.

Take care,
Keshia
