### ISSUE TITLE
Problems with automated deployment due to repo structure

### ISSUE THREAD

**Issue by kabelak** [tableau/extension-data-driven-parameters#46]
I have an automated deployment method for pulling and publishing extensions in a self-hosted tableau-extensions server. The current folder contents have trex files named as `<extension>v2.0.0.trex` and `<extension>v2.1.0.trex`, while other tableau extensions repos are just `<extension>.trex`.

Can we tag the repos with versions, so that people requiring a specific version can checkout the appropriate tag, and make this repo have only one .trex file as `<extension>.trex`?

That would be very much appreciated

**Comment by KeshiaRose** [comment]
Hi @kabelak,

I've changed the trex file to be for all v2 updates (`DataDrivenParameters_2.latest.trex`) that way you can just pull that one file and won't have to change it for minor updates. Does this help with your situation?

Take care,
Keshia

**Comment by kabelak** [comment]
Hi @KeshiaRose,
It's better in some ways, but still doesn't match the way the other repos work. the requirement to copy the `.trex` to a folder called `2.latest`, which I assume would change with versions, is still a challenge for automated deployments. I appreciate there may be requirements, and if so, apologies, but having a single `.trex` populated with a static folder structure, would be awesome. 

eg: 
<url>https://tableau.github.io/extension-data-driven-parameters/2.latest/#/parameter</url>
v/s
<url>https://tableau.github.io/extension-parameter-actions/#/paramact</url>

**Comment by KeshiaRose** [comment]
Hi @kabelak,

I see, the most I can say is that I won't be updating from v2 for quite some time so your automated systems should be fine. Besides, and any major version number updates will include breaking changes.

Take care,
Keshia
