### ISSUE TITLE
Extension broken

### ISSUE THREAD

**Issue by RocketmanJoe** [tableau/extension-data-driven-parameters#47]
I've used this extension for a while now but this week it stopped working for me. After clicking a value in a worksheet the extension used to provide a drop down of a filtered list, now however it just says "Parameter Needs Configuration". I realised there is a new version 2.1 and I tried to use that however when I click a dashboard action the extension will remove all filters and jump to the the first value it fines, rendering it useless. This is a very useful tool when it works, any ideas what happened this week to stop it from working?

**Comment by KeshiaRose** [comment]
Hi @RocketmanJoe,

Nothing was changed about the older versions this week so not sure why it suddenly stopped working for you. If you can put together a sample workbook where you are seeing the issue I can take a look at it for you.

Take care,
Keshia

**Comment by RocketmanJoe** [comment]
Hi KeshiaRose,

Thanks for getting back to me. The issue seems to be that the Data-driven parameter isn't updating until I actually click a value in it and it is initially empty so it won't come up with any values (hence the Parameter needs Configuring. I used your workaround solution https://glitch.com/edit/#!/param-listener-workaround?path=README.md:1:0 but that didn't seem to work. Is there configuration on this I need to do for it to work online?
I noticed that it is only an issue on Tableau server and works fine offline so I'm not sure if it's related to a Tableau update. I may be able to mock up a workbook for you but the data is quite sensitive at the moment.

RocketmanJoe

**Comment by KeshiaRose** [comment]
Hi @RocketmanJoe,

Have you tried the new "Update list when a parameter changes." option in the latest version? There is no separate configuration for the extension to work on Server or Online. Feel free to use the superstore data for the mock-up if you are still having the issue with the latest version.

Take care,
Keshia

**Comment by KeshiaRose** [comment]
Hi @RocketmanJoe,

I'm going to close this as it has been a while, please feel free to re-open if you are still having this issue.

Take care,
Keshia
