### ISSUE TITLE
Issue with wss not able to configure the code on premises

### ISSUE THREAD

**Issue by SameerRathod** [tableau/extension-data-driven-parameters#49]
Hi, 
I am trying to set up this code on my server. The first issue I am getting this the code is not running on https. I have written a proxy server in nodejs but I am getting an error of WebSocket. Can somebody help me with what I am doing wrong?

**Comment by KeshiaRose** [comment]
Hi @SameerRathod,

Sorry for the delayed response I've been out of town for a while. If you are trying to run the extension on your own server you will need to set up your server with your own certificate. What process have you done so far in hosting it on your own?

Take care,
Keshia

**Comment by SameerRathod** [comment]
No worries, I resolved the issue. The issue was for prod deployment we need
to create a static build and paste the same in hosting server. What I was
doing is, I was using the dev setup with the react-scripts run command. In
the case of dev, it was not picking up the SSL certificate from the
react-native SSL folder.

Thanks

**Comment by KeshiaRose** [comment]
Aha! Thanks for coming back and sharing your process so it may help others in the future!
