### ISSUE TITLE
Use different field for display values. Sorting issue.

### ISSUE THREAD

**Issue by morganrainey** [tableau/extension-data-driven-parameters#50]
When using the 'Use different field for display values' option, sorting does not occur on the new field but rather the original field.

**Comment by morganrainey** [comment]
As a use case, I have a value called affordability. Something is deemed affordable if it is less than this percentage of a person's income. The affordability rate goes up and down from year to year. So currently my years are not being listed in order. The year is what the person chooses and it populates the affordability parameter, which can also be customized outside of the year.

**Comment by KeshiaRose** [comment]
Hi @morganrainey, 

Yes, this is as designed but there is an open feature request (#9) to allow sorting based on different values. However, I am trying to understand your use case for when I work on that feature later. Your extension is based on year, and they are in order originally but then you are using a different value for display and those values are not sorted, right. What field are you using for display?

Take care,
Keshia

**Comment by KeshiaRose** [comment]
Hi @morganrainey, 

I'm going to close this as there is a similar request already created. You didn't get back to me with more details but from what you said one possible solution would be to use the year as the actual value and not the display value. Then you could have a case statement based on the year with the appropriate affordability value for the year and use that in your calculations etc. 

Ex: CASE [Year Param]
WHEN 2018 THEN .2
WHEN 2019 THEN .25
etc.

Take care,
Keshia
