### ISSUE TITLE
Summary of v2.1 changes

### ISSUE THREAD

**Issue by MattVoda** [tableau/extension-data-driven-parameters#51]
Hey Keshia,

I've got a bit of time and am considering upgrading to v2.1, but I'm not clear on what's new / different and what might break. 
From reading your commits, one point seems to be that the extension 'refreshes' when the parameter value changes -- is this equivalent to the 2.0 config option for 'Update list of values on param change'? We don't use this, so having it as a default might be reason to avoid..

If you have a min, would love a little changelog / advice on how usability might differ. Also, apologies if I'm blowing a minor update out of proportion!

--Matt

**Comment by KeshiaRose** [comment]
Hey Matt,

Great question! That comment is about a new option "Update selection if source parameter changes." It will not do this on default, only when you enable the new option. There are no changes to the default behavior. You should have the same experience with 2.0 with just some new options. The other changes were just around event listener cleanup and some logical refactoring.

I'll make sure to be more detailed in the commit notes next time as it does sound quite vague looking back on it. Let me know if you come across any issues, hope this helps!

Take care,
Keshia
