### ISSUE TITLE
To use this extension why it require internet connectivity

### ISSUE THREAD

**Issue by ANILSARAN** [tableau/extension-data-driven-parameters#54]
We are consuming this extension in one of our tableau dashboard. However it is not working on machine where internet connectivity is not there. Would like to know the reason behind to use this extension why it require internet connectivity and also is there any other way it can be work .
Looking forward for your answer...

**Comment by KeshiaRose** [comment]
Hi @ANILSARAN, 

All extensions are required to be hosted somewhere, even just on localhost, in order to run. Offline extensions do not exist. This makes it possible to share extensions without packaging the entire source code. However, the extension is fully open source so you are free to download it and run it locally on your offline machine!

Take care,
Keshia

**Comment by ANILSARAN** [comment]
Thanks Keshia.
I need one more confirmation so can you please confirm it.
We are the OEM partner of Tableau and we are consuming this extension.
Can you confirm it that this extension is not using/consuming the underlying data of dashboard by any means to the hosted site ?

And also it has been reported by one of our customer that after consuming this extension in dashboard the dashboard is not showing any data. The reason what we found that they have restriction on site. So in this case do we need to add exception for following url  to allow/access hosted site:
https://tableau.github.io/extension-data-driven-parameters/2.0.0/#/parameter



Regards,
Anil Saran

**Comment by KeshiaRose** [comment]
Hi @ANILSARAN,

Yes, I can confirm that the extension does not send any of the underlying data of the dashboard anywhere. This extension is hosted right here out of this repo as you can see so you can also verify that if you would like to look at the source code. 

Also yes, you will need to add the extension URL to your [safe-list](https://help.tableau.com/current/server/en-us/dashboard_extensions_server.htm#add-extensions-to-the-safe-list-and-configure-user-prompts) for it to run. Your users will also need to have permission to view summary data.

If you are on 2019.3 or higher and would like an even stronger confirmation of the data security you can use the sandboxed version of this extension found [here](https://extensiongallery.tableau.com/products/101?version=2019.4). Sandboxed extensions run in a protected environment without access to any other resource or service on the web, you can read more about them [here](https://help.tableau.com/current/server/en-us/dashboard_extensions_server.htm#before-you-run-extensions-on-tableau-server).

Hope this helps!
Keshia
