### ISSUE TITLE
Feature Request: update list when a parameter changes

### ISSUE THREAD

**Issue by ghost** [tableau/extension-data-driven-parameters#57]
when this option is enabled, during the change in the parameter list it changes correctly by selecting the first item in the list, because the option of 'all' is not set first if it is activated.

You can put a checklist in 'update list when a parameter change' so that you have more options in case other parameters also depend on that option

thanks

**Comment by juan619** [comment]
this is with version sandbox

**Comment by KeshiaRose** [comment]
Thanks for the idea @juan619, I'll consider it!
