### ISSUE TITLE
OK button not closing the parameter configuration dialog

### ISSUE THREAD

**Issue by agladshteyn** [tableau/extension-data-driven-parameters#58]
After selecting the values in the "Data-Driven Parameter Configuration" dialog, OK button does not work.  It does not close the dialog and does not actually save anything.  Tableau version: 2019.4.0

**Comment by KeshiaRose** [comment]
Hi @agladshteyn,

Sorry for the delayed reply, are you using Mac or Windows?

Take care,
Keshia

**Comment by agladshteyn** [comment]
Hello. I am using Windows 10.
________________________________

**Comment by KeshiaRose** [comment]
Hmm, could you try running Desktop in [debug mode](https://tableau.github.io/extensions-api/docs/trex_debugging.html) and see if you get any errors in the console? You are using version 2+ of the extension right?

**Comment by sahilagarwal** [comment]
I am facing a similar issue. Do we have a resolution for this?

**Comment by KeshiaRose** [comment]
Hi @sahilagarwal,

Thank you for the error screenshot in #60. It looks like one of the settings being saved is undefined which is causing the issue. This should not be the case with the validations for the settings so I'm curious if it something specific to your environment. Could you please try using the [latest version](https://cdn.jsdelivr.net/gh/tableau/extension-data-driven-parameters@master/DataDrivenParameters_2.latest.trex) of the extension and trying it with the superstore dashboard. Just make a simple string parameter first so you have something to use. Also, what version of Tableau are you using?

Take care,
Keshia

**Comment by KeshiaRose** [comment]
Hi Sahil,

The version you sent looks like it is being hosted locally. If you pulled those files from [2.latest](https://github.com/tableau/extension-data-driven-parameters/tree/master/docs/2.latest) it should be the exact same code as the one I sent you. I can't replicate the issue on my end so it is hard for me to troubleshoot. Were you able to try it with superstore?

Take care,
Keshia

**Comment by KeshiaRose** [comment]
I believe I've found the bug and fixed the issue. I'm going to close this, please reopen if you're still seeing it.
