### ISSUE TITLE
Possible interference with JS api's 'viz' object?

### ISSUE THREAD

**Issue by MattVoda** [tableau/extension-data-driven-parameters#59]
Hey Keshia,

I've been playing around with the JS api (v2.2.2) for the last few days after embedding some of our dashboards into an Angular web app.
A frustrating limitation I'm running into concerns the the **viz** object (created by this.viz = new tableau.Viz(containerDiv, url, options)).
My viz objects, for all dashboards, return null when I run viz.getWorkbook(), likely because they're missing _$1a_ on __impl_ within the viz object. Without access to the workbook object, I can't do anything fun! 
I'm doing all this in _.onFirstInteractive()_ so the viz is definitely initialized at the point .getWorkbook() is run, though it does reload with DDP param data. 

No success finding others with this strange missing-workbook problem, so I'm wondering if one of my extensions might be responsible. 
I'd love any thoughts or advice you might have on this!!

Happy-soon-holidays :)
--Matt

**Comment by MattVoda** [comment]
Fixed by using JS api v2.3.0
::facepalm::

**Comment by KeshiaRose** [comment]
😄 love these, thanks for the update Matt!
