### ISSUE TITLE
Unable to save configuration settings, "OK" button not working after selecting the appropriate fields in 'Configure Window'

### ISSUE THREAD

**Issue by sahilagarwal** [tableau/extension-data-driven-parameters#60]

**Comment by sahilagarwal** [comment]
![image](https://user-images.githubusercontent.com/13720124/70990065-c8b59180-20ea-11ea-9c79-d2f7865bce0c.png)

This is what I am able to see when I am hitting the OK button in debugging mode.

**Comment by KeshiaRose** [comment]
Just closing this to clean up issues, original still open.
