### ISSUE TITLE
Page Reloads after the initial load

### ISSUE THREAD

**Issue by esaravana01** [tableau/extension-data-driven-parameters#61]
I 'm not sure if this is an issue or if it is meant to work this way. When ever the page completes loading the dashboards(from tableau server), it again reloads to populate the values in the parameter box. Since our dashboards are complex, it takes 30 seconds to do the initial load and then it takes additional 10 seconds to load the Data Driven parameter box.

**Comment by KeshiaRose** [comment]
Hi @esaravana01,

Yes, this is by design, the parameter needs to load after the dashboard loads so it can get the right data from the worksheets. 

Take care,
Keshia
