### ISSUE TITLE
Showed value

### ISSUE THREAD

**Issue by vasilevskyvitaly** [tableau/extension-data-driven-parameters#66]
When the value is updated using another parameter and the "All" option is turned on, that is, at the time of switching that parameter, the value of which is set first in the list (first after "all" value), but "All" is displayed as chosen.

**Comment by KeshiaRose** [comment]
Hi @vasilevskyvitaly,

Thanks for the heads up! Just pushed a fix, let me know if it works for you!

Take care,
Keshia
