### ISSUE TITLE
I had the same situation, and I found a workaround I needed to add a minimum of 2 parameters in the workbook then button 'OK' works.

### ISSUE THREAD

**Issue by Mirek-sikora** [tableau/extension-data-driven-parameters#67]
I had the same situation, and I found a workaround I need to add a minimum of 2 parameters in the workbook then button 'OK' works.

_Originally posted by @Mirek-sikora in https://github.com/tableau/extension-data-driven-parameters/issues/48#issuecomment-577658413_

**Comment by KeshiaRose** [comment]
Correct, it was having an issue with setting one of the options to undefined because there were no other parameters. You opened this issue but you aren't seeing it still, right? I'm going to close this but please let me know if you are still having issues!
