### ISSUE TITLE
Ability to trigger the parameter update(s) before any data refreshes

### ISSUE THREAD

**Issue by geoff-bbc** [tableau/extension-data-driven-parameters#69]
Hi KeshiaRose,

Thanks for your work on this extension! I know the community has been asking for quite a while about "Latest Date" filters. I appreciate that it was delivered in the core application for Discrete Dates but we've been waiting for the same abilities in Date Ranges. I recently found your extension and have been making it work for one of my clients.

Background:
- I'm using the sandboxed extension version with Tableau 2019.4 desktop
- Dashboards are distributed by publishing to a Tableau Online account
- main purpose is to allow the end-users to see a default data date range of EndDate: latest date in data and StartDate: EndDate - 7 days, while still being able to use the calendar date selector to set different start and end dates for ad-hoc queries. (which can't be done in Relative Date Selector)

Proposed Enhancement:
 - Is it possible to have an extension setting that allows the parameters to get updated before any dashboard/worksheet refreshes take place?
- Consider that my Start Date and End Date parameters are set to 1/1/20 and 1/8/20 at the time I publish the dashboard. The user experience is that they see the rendered dashboard for this time range and then after a 2 second delay the extension driven parameters switch to 1/19 and 1/26 and the worksheets all refresh to show the updated correct data.
- It would be great if the 1/19 and 1/26 (examples) could somehow get set in the background so that the dashboard only renders once with these parameters.

Possible? Thanks in advance.

**Comment by KeshiaRose** [comment]
Hi @geoff-bbc,

Thanks for the feedback, it's always interesting for me to hear how folks are using extensions! 😃 

Unfortunately, this is something that comes from the way extensions work as a whole and is not specific to this extension. Currently, all extensions get loaded after the dashboard. This is because the extension needs to look at the dashboard for the data it uses. This means however that you end up with double-loading a dashboard if the extension makes updates immediately. 

One idea you could do as a workaround is to set the parameters to something that does not return any data so the first load is faster and less noticeable. However, this isn't something I can fix from within the extension. 😞

On the bright side, this is a feature that is slated to be added in-product in 2020.1! Check out the [beta ](https://prerelease.tableau.com/project/home.html?cap=5c890c1ddfc84f1fbb7c616f2dbd8222)to try it out!

Take care,
Keshia

**Comment by geoff-bbc** [comment]
Hi @KeshiaRose,

I was excited to hear this would be supported in 2020.1, sorry I forgot to reply as such!

I just installed 2020.1 and am looking to accomplish what I described in this issue. I've followed ALL of the documentation I can find, but I seem to be missing something.

I have created a calculated field with formula: `MAX([Tradedate])` but that field is not showing up as a choice for 'Value When Workbook Opens'. I've checked data types - they're both Date.
The updated documentation seems to emphasize _**single-value, view-independent calculation**_ but when I search the KB for that phrase there aren't any other definitions.

Were you involved in the new feature planning or testing? Do you know what I'm missing here?

Thanks,
Geoff

**Comment by KeshiaRose** [comment]
Hi @geoff-bbc,

You are so close! The key here is "view-independent calculation". Aggregate calculations change their results depending on what dimensions are on the detail of the view. You will need to use a calculation that returns the same value no matter what. That can either be a row-level calculation/field or in your case, an LOD calculation: `{MAX([Tradedate])}` 😉 

Take care,
Keshia

**Comment by geoff-bbc** [comment]
Worked like a charm! Thanks for your help Keshia! ❤️

**Comment by geoff-bbc** [comment]
Hi @KeshiaRose,

I don't want to misuse this thread. Is there an official channel for posting potential bugs with the new release?

My situation is that I have implemented the 'Value When Workbook Opens' parameter feature as discussed here. It works as expected when I open a workbook in Tableau Desktop. When I open the same dashboard as a view in Tableau Online the date is not reliably updating. I am Ctrl-clicking the refresh button in Chrome which should force a non-cached refresh, which is more than I can likely expect from my end users, and even though I know I have data from 2/29 for example, the parameter remains incorrectly set to 2/28.
This client of mine is on https://eu-west-1a.online.tableau.com/. Are all the Tableau Online nodes ready to support 2020.1?

Thanks,
Geoff

**Comment by KeshiaRose** [comment]
Hi @geoff-bbc,

All Tableau Online pods always get the upgrades before we release Desktop, you can confirm the version by going to the question mark in the top right and selecting "About Tableau Online". That being said it must be something else. Can you try making a simple test workbook with the superstore data set and seeing if that works? As far as the best place to put this, if it still doesn't work with just a simple sample I would reach out to support here: [https://www.tableau.com/support/case](https://www.tableau.com/support/case)

Take care,
Keshia
