### ISSUE TITLE
inconsistency between trex and build files

### ISSUE THREAD

**Issue by kabelak** [tableau/extension-data-driven-parameters#70]
Good work on the extensions and keeping them on github. I had a problem with the deployment of this one:
Is it normal that the asset-manifest.json and .trex file reference a different directory structure? Please let me know if I'm missing something.

`asset-manifest.json
{
  "files": {
    "main.css": "/extension-data-driven-parameters/static/css/main.2b70444d.chunk.css",
    "main.js": "/extension-data-driven-parameters/static/js/main.65f84886.chunk.js",
    "main.js.map": "/extension-data-driven-parameters/static/js/main.65f84886.chunk.js.map",
    "runtime~main.js": "/extension-data-driven-parameters/static/js/runtime~main.01d56cb3.js",
    "runtime~main.js.map": "/extension-data-driven-parameters/static/js/runtime~main.01d56cb3.js.map",
    "static/js/2.b6686ab4.chunk.js": "/extension-data-driven-parameters/static/js/2.b6686ab4.chunk.js",
    "static/js/2.b6686ab4.chunk.js.map": "/extension-data-driven-parameters/static/js/2.b6686ab4.chunk.js.map",
    "index.html": "/extension-data-driven-parameters/index.html",
    "precache-manifest.65cbc4f640e7148af565096ee4c6204d.js": "/extension-data-driven-parameters/precache-manifest.65cbc4f640e7148af565096ee4c6204d.js",
    "service-worker.js": "/extension-data-driven-parameters/service-worker.js",
    "static/css/main.2b70444d.chunk.css.map": "/extension-data-driven-parameters/static/css/main.2b70444d.chunk.css.map"
  }`

Trex file:
`<?xml version="1.0" encoding="utf-8"?>
<manifest manifest-version="0.1" xmlns="http://www.tableau.com/xml/extension_manifest">
  <dashboard-extension id="com.tableau.extensions.datadrivenparamsummary" extension-version="2.1.0">
    <default-locale>en_US</default-locale>
    <name resource-id="name"/>
    <description>Automatically update your parameters based on your data!</description>
    <author name="Tableau" email="devplat@tableau.com" organization="Tableau" website="https://www.tableau.com"/>
    <min-api-version>0.9</min-api-version>
    <source-location>
      <url>https://<redacted_for_git>/extension-data-driven-parameters/2.latest/#/parameter</url>
    </source-location>`

**Comment by KeshiaRose** [comment]
Hi @kabelak,

Thanks for the feedback! It looks like you are looking at the asset manifest file for version 1.0 of the extension which is hosted at `/extension-data-driven-parameters/` from the `/docs/` folder but comparing it to 2.latest which is hosted at `/extension-data-driven-parameters/2.latest/` from `/docs/2.latest/`. Here is the asset manifest you should compare the trex to: https://github.com/tableau/extension-data-driven-parameters/blob/master/docs/2.latest/asset-manifest.json

Hope that helps!
Keshia

**Comment by kabelak** [comment]
@KeshiaRose does that mean the contents of the `docs/2.latest` need to be copied to the deployment, rather than the contents of the `build/` folder? The `asset-manifest.json` I pasted up there was from the `build/` folder. Please advise!

**Comment by KeshiaRose** [comment]
@kabelak, yup, grab from `docs/2.latest` I'll update the readme instructions to match!

**Comment by KeshiaRose** [comment]
@kabelak if you want to run the extension locally make sure to follow the instructions in the README. You will need to update the homepage (as you saw in the asset manifest file) to match your setup. The output of your custom build will be in the `build` folder.

**Comment by kabelak** [comment]
@KeshiaRose OK thanks for the tip; 

My confusion stems from the .trex file not being updated upon yarn build - Should the parent folder .trex be updated for the url during the build, or should that be updated manually? Or am I (again) missing something?

**Comment by KeshiaRose** [comment]
I see, yes the .trex file needs to be updated manually to match where you're hosting it.

**Comment by KeshiaRose** [comment]
I've updated the instructions to reflect this as well.
