### ISSUE TITLE
Unable to configure extension in my Tableau desktop

### ISSUE THREAD

**Issue by karthi-ck** [tableau/extension-data-driven-parameters#72]
Hi,
https://community.tableau.com/thread/303745
I am facing similar issue as posted in the above link.
I want to test some dashboard extensions and have downloaded data driven extension from the Extensions gallery. When I bring either one of these into a dashboard in my workbook, the extension summary pops up but I cannot figure out how to configure. Selecting the configure option does not seem to do anything. I am on desktop 2019.2.8. It works fine in Tableau server after publishing. Only in my system i am getting this issue but in other's system, i can able to configure. Is is due to any proxy permission settings in my desktop?

Please help.

**Comment by KeshiaRose** [comment]
Hi @karthi-ck,

Could you take a look at the console and see if any errors are coming through? You can learn how to set up the debugger [here](https://tableau.github.io/extensions-api/docs/trex_debugging.html#start-tableau-desktop-and-enable-debugging-windows). It definitely is something specific to your machine but I'm not sure what. Let me know if you see any errors there and I can try and troubleshoot.

Take care,
Keshia

**Comment by karthi-ck** [comment]
Hi @KeshiaRose ,
The issue was due to some proxy settings in our organization which blocks the extension from communicating to external sites. Could you please share the list of external URLs which will be needed by this extension to work so that I can check with my admin team to add them in our proxy server if possible.

**Comment by KeshiaRose** [comment]
Hi @karthi-ck, 

Glad you were able to figure out the issue! The extension is fully hosted on `https://tableau.github.io/extension-data-driven-parameters/` and does not reach out to any external resources. If you are using the sandboxed version that is hosted on `https://extensions.tableauusercontent.com/sandbox/data-driven-parameters/`.

Take care,
Keshia
