### ISSUE TITLE
Workbook Permissions for Parameter

### ISSUE THREAD

**Issue by lanamitchell** [tableau/extension-data-driven-parameters#75]
We were experiencing a constant refresh of views that use the data driven parameter. By this, I mean that the dashboard does not completely load before it refreshes and tries to load again.

Please note that we are using custom permissions on our workbooks instead of the existing template permissions provided by Tableau Server 2020.1.

This refresh issue stopped when we allowed Download of Summary Data for the workbooks using the data Driven parameter extension. 

Can you advise what workbook permissions are required for the extension to function as expected?

**Comment by KeshiaRose** [comment]
Hi @lanamitchell,

Yes, this is a requirement of the extension to work properly. Getting access to the tableau parameter requires a summary data level of permissions. Unfortunately, we currently have a bug that when this permission is denied, it refreshes the dashboard. We have just last week coded a fix for this problem that will simply stop the extension from working without constantly refreshing the dashboard. This fix is currently set to be released with 2020.3 which _should_ come out sometime in August (no promises).

Take care,
Keshia
