### ISSUE TITLE
Values not shown when dashboard downloaded as PDF

### ISSUE THREAD

**Issue by deepikatr** [tableau/extension-data-driven-parameters#82]
Hello,
While downloading the dashboard as a PDF/Image the values are not shown for the data driven parameters. 

This is the screenshot of the dashboard with the extension
![PA dashboard](https://user-images.githubusercontent.com/13363801/92090196-c916c980-edec-11ea-92c2-f27d72836013.PNG)
The same dashboard when downloaded as a PDF/Image
![PA pdf](https://user-images.githubusercontent.com/13363801/92090236-d16f0480-edec-11ea-998d-1ea8023fdf55.PNG)

Downloading the dashboard as an Image/PDF is a much needed feature for our product.

Thanks,
Deepika

**Comment by KeshiaRose** [comment]
Hi @deepikatr, this is a limitation of the Extensions API in general. It is something we are working on but has proven difficult to do. Please follow this issue for updates: https://github.com/tableau/extensions-api/issues/309 
-Keshia

**Comment by deepikatr** [comment]
Thank you for the update !
