### ISSUE TITLE
Automatically date parameter using calculated field and data driven parameters

### ISSUE THREAD

**Issue by andrew1022** [tableau/extension-data-driven-parameters#85]
Hi, this is a great extension! I have a parameter with options for time periods (e.g. specific fiscal periods, weeks, custom, etc.). When a time period is selected, two different calculated fields are used to calculate the start and end date of the period. I am trying to use data-driven parameters to take the results of the calculated date fields and place them into two date parameters, one for start date and one for end date. I need to use parameters to display these dates instead of calculated fields because the "custom" option needs to allow users of the dashboard to alter the dates. 

Is it possible to update the list of options in the extension automatically when the selected date period is changed? I want to avoid having users of the reports need to click "reload" on each of the extensions for the correct dates to appear. Thanks in advance!

**Comment by KeshiaRose** [comment]
Hi @andrew1022, there is an option to update the extension based on changes in a parameter. "Update list when a parameter changes." with a dropdown. Would this work?
-Keshia

**Comment by andrew1022** [comment]
@KeshiaRose, that worked! I had missed that setting before, thanks for the help. -Andrew

**Comment by KeshiaRose** [comment]
Awesome! 😄
